apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopfexample-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kopfexample-operator
  template:
    metadata:
      labels:
        application: kopfexample-operator
    spec:
      serviceAccountName: kopfexample-account
      containers:
      - name: the-only-one
        image: mowassmer/task4:1.0.2
        imagePullPolicy: Always #IfNotPresent
        env:
        - name: WORKLOAD_SCHEDULING_PERIOD
          value: "10" # Default scheduling period in seconds
        - name: SCHEDULING_STRATEGY
          value: "random" # Default scheduling strategy