---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "default"
  name: scheduler-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [get, list, watch, patch]
  
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]    

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
  - apiGroups: [admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application
  - apiGroups: [""]  # Core API group
    resources: [namespaces, events, pods, pods/status, persistentvolumeclaims, nodes]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [extensions]
    resources: [jobs]
    verbs: [get, list, watch, create, update, delete]
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [get, list, watch, create, update, delete]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  # TODO: cleanup
  - apiGroups: [""]  # Core API group
    resources: [events, pods, pods/status, persistentvolumeclaims]
    verbs: [get, list, watch, create, update, patch, delete]

  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [get, list, watch, create, update, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: scheduler-role-namespaced
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduler-role-cluster
subjects:
  - kind: ServiceAccount
    name: scheduler-account
    namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: scheduler-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduler-role-namespaced
subjects:
  - kind: ServiceAccount
    name: scheduler-account
