---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "default"
  name: kopfexample-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopfexample-role-cluster
rules:
  # Framework and application permissions
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings, kopfexamples, kopfpeerings]
    verbs: [get, list, watch, patch, create, update, delete]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch, delete]
  - apiGroups: [""]  # Core API group
    resources: [namespaces, events, pods, persistentvolumeclaims]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [get, list, watch, create, update, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: kopfexample-role-namespaced
rules:
  # Namespaced-specific permissions
  - apiGroups: [kopf.dev]
    resources: [kopfexamples, kopfpeerings]
    verbs: [get, list, watch, patch, create, update, delete]
  - apiGroups: [""]  # Core API group
    resources: [events, pods, persistentvolumeclaims]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [get, list, watch, create, update, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopfexample-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopfexample-role-cluster
subjects:
  - kind: ServiceAccount
    name: kopfexample-account
    namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: kopfexample-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kopfexample-role-namespaced
subjects:
  - kind: ServiceAccount
    name: kopfexample-account
