apiVersion: v1
kind: Pod
metadata:
  name: simulated-workload
  labels:
    app: workload-simulation
spec:
  containers:
  - name: workload-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep $((RANDOM % 21 + 40))"]
  restartPolicy: Never
