apiVersion: v1
kind: Pod
metadata:
  name: simulated-workload
  labels:
    app: workload-simulation
spec:
  containers:
  - name: workload-container
    image: severalnines/sysbench
    command: ["/bin/sh", "-c"]
    args:
      - |
        duration=$((RANDOM % 41 + 20));
        echo "Running sysbench for $duration seconds...";
        sysbench cpu --time=$duration run;
        echo "Sysbench completed.";
  restartPolicy: Never
